### PR TITLE
(MODE-11589) Setup one-to-one styling with the maps server previous version

### PR DESCRIPTION
**Pull request by dobrevkalm**
Updated as much as I could. Some of the local names are still an issue. There are details such as minor roads, road labels and boundaries that are showing up at different zoom level then the ones on the production. 

Also the country name Canada does not exist for some reason...

https://monosupport.atlassian.net/browse/MODE-11589

### CODE REVIEW

**Comment by dobrevkalm** [comment]
There were some issues that were fixed when we were checking the mentioned coordinates, however, all the main difference is basically caused by the zoom levels in the new data set.

**Comment by dobrevkalm** [comment]
Fixed the missing icons by adding a layer that covers all the classes that does not have an icon in the sprites (all that we know of so far) and shows a default "marker" icon.

In order to fix some of the non-showing colleges/schools and hotels, I created a poi_label_important_rest that will adjust the zoom level for any class that has higher rank.

**Comment by dobrevkalm** [comment]
All the points/icons except for the airport and the playground were showing the same way as on the production for me. If you can double check, I'll look at them later.

**Comment by siozosdr** [comment]
@dobrevkalm yeah the playground and the airport look good now bu the points with `class: place_of_worship` still have no icons showing

**Comment by dobrevkalm** [comment]
It does when I open it. Both in the editor and test.monomaps.

image

image

**Comment by dobrevkalm** [comment]
We just found out that opening the maps in the browser normally and in incognito mode is different. Don't know what is causing the issue since I have caching disabled.

image

image

**Pull request merged**
